### ISSUE TITLE
path.js:28     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');

### ISSUE THREAD

**Issue by capsulecorplab** [aragon/hack#2]
Installed `aragon-dev-cli` using `npm install -g @aragon/cli`.

Running `aragon-dev-cli init [your-app-name].open.aragonpm.eth [boilerplate: "react" or "bare", defaults to "react"]` or `aragon-dev-cli playground` throws error:

```
path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1179:7)
    at module.exports (/home/saiyaman/.npm-global/lib/node_modules/@aragon/cli/src/config.js:6:28)
    at Object.<anonymous> (/home/saiyaman/.npm-global/lib/node_modules/@aragon/cli/src/pkg.js:4:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
```

Running node v9.4.0, npm v5.6.0

**Comment by onbjerg** [comment]
What's the actual command you ran?

**Comment by capsulecorplab** [comment]
I tried `aragon-dev-cli init registry.aragonpm.eth bare`, `aragon-dev-cli init registry.aragonpm.eth react`, and `aragon-dev-cli playground`, all of which throw the same error.

**Comment by renexdev** [comment]
´npm init´ first in your workspace clean directory

**Comment by capsulecorplab** [comment]
Thanks @renexdev! Yes, it was missing the `package.json` file.
@bingen perhaps you should reopen the PR for #1 ?

**Comment by bingen** [comment]
Well, it seems that this one fixes the issue too:
https://github.com/aragon/aragon-dev-cli/pull/32

**Comment by tabishsudofy** [comment]
while deploying my application on github pages i got an error plzz tell me what should i do..
>>>>ngh



    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:495:7)
    at promptCreds (C:\Users\Sardar Tabish Zaman\AppData\Roaming\npm\node_modules\ngh\bin\ngh:11:24)
    at Object.<anonymous> (C:\Users\Sardar Tabish Zaman\AppData\Roaming\npm\node_modules\ngh\bin\ngh:110:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)

**Comment by onbjerg** [comment]
@tabishsudofy I have no idea what ngh is. Are you in the correct repository?
