### ISSUE TITLE
Error in "Your first Aragon app" tutorial

### ISSUE THREAD

**Issue by ghost** [aragon/hack#55]
I tried following this ["Your first Aragon app" tutorial](https://hack.aragon.org/docs/tutorial.html). When I run `aragon run` command, got an error bellow:

```
 ❯ Start a local Ethereum network
   ⠴ Setting up a new chain from latest Aragon snapshot
     Starting a local chain from snapshot
   Check IPFS
   Publish app to APM
   Create DAO
   Open DAO

/Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/level-codec/index.js:44
  return this._valueEncoding(opts).decode(value)
                                   ^
SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse [as decode] (<anonymous>)
    at Codec.decodeValue (/Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/level-codec/index.js:44:36)
    at /Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/level-sublevel/nut.js:122:34
    at /Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/encoding-down/index.js:57:5
    at /Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/cachedown/index.js:61:5
    at /Users/yutaro/.nodebrew/node/v9.5.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/lib/database/filedown.js:28:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```

**Comment by sohkai** [comment]
Issue moved to [aragon/aragon-cli #274](https://github.com/aragon/aragon-cli/issues/274).
